### ISSUE TITLE
lookup the right edge of a Hist

### ISSUE THREAD

**Issue by YabusameHoulen** [Moelf/FHist.jl#128]
非常方便的包，谢谢😁👍
```
julia> a = Hist1D([1,1,1,2,2,3], binedges=1:3)
edges: [1.0, 2.0, 3.0]
bin counts: [3.0, 2.0]
total count: 5.0

julia> lookup(a, 3)
ERROR: BoundsError: attempt to access 2-element Vector{Float64} at index [3]

julia>lookup(a,0.9), lookup(a, 1), lookup(a,2), lookup(a, 3.1)
(missing, 3.0, 2.0, missing)
```
`lookup`对`binedges`判断条件`!(first(r) <= x <= last(r)) && return missing`
`searchsortedlast`查找右端点索引超过`bincounts`, 应该指定返回`missing`或者`1.0`吗 ？

**Comment by Moelf** [comment]
hi! glad you find the package useful -- indeed this looks like a bug.

Technically, since bins are basically closed on the left, `3` shouldn't be included and this should return missing.
