### ISSUE TITLE
Useful functionality

### ISSUE THREAD

**Issue by aminnj** [Moelf/FHist.jl#13]
Let me list some functionality from [`yahist`](https://github.com/aminnj/yahist/blob/master/yahist/hist1d.py) that I found useful (used >=1 times) in the past year. Feel free to make a concrete todo list of whichever ones you think make sense in Julia.

* `+-/*` operators
* `h.counts`
* `h.errors`
* `h.edges`
* `h.bin_centers`
* `h.nbins`
* `h.integral`
* `h.mean()`/`h.std()`/`h.median()`
* `h.normalize()`
* `h.rebin(3)` to combine 3 adjacent bins into one
* `h.restrict(self, low=None, high=None)` to subset the hist along the x-axis
* `h.cumulative()`
* `h.lookup()` which takes x-value(s) and returns the bin content(s). E.g.,
```julia
lookup(h::Hist1D, value) = h.hist.weights[FHist._edge_binindex(h.hist.edges[1], value)]
h1 = Hist1D(Int; bins=0:3)
push!.(h1, [0.5, 1.5])
@test lookup.(h1, [0.5,1.5,2.5]) == [1, 1, 0]
```
* `h.quantile()` (`h.quantile(0.5)` is used for `h.median()` above)
* `h.sample()`
* `h.to_json()`, `h.from_json()` for de/serialization

**Comment by Moelf** [comment]
I wonder if we can deligate to Distributions for the stats stuff, like cumulative, mean etc. technically histogram is a mass distribution function?

**Comment by aminnj** [comment]
Came across this, but it seems a little hacky to make a distribution for each bin.
https://discourse.julialang.org/t/using-a-normalized-histogram-as-a-distribution/27682/16
And from later in that thread, it looks like the basic `mean`, `std`, `quantile` are implemented by hand anyway:
https://github.com/bat/BAT.jl/blob/abe2713f95754abb8fc536610af89c6dc75c2d38/src/distributions/HistogramAsUvDistribution.jl

**Comment by aminnj** [comment]
After PR https://github.com/Moelf/FHist.jl/pull/14, what's left is:

* `h.rebin(3)` to combine 3 adjacent bins into one, and `h.restrict(self, low=None, high=None)` to subset the hist along the x-axis

* `h.to_json()`, `h.from_json()`

**Comment by Moelf** [comment]
Hmmm I used to have a rebin somewhere :|

Do we have a reference to what JSON should look like?

**Comment by aminnj** [comment]
ROOT is too boomer to have json serialization I think, but for yahist it looks like
```json
{
  "_counts": [
    9808,
    82973,
    7219
  ],
  "_edges": [
    -4.040355849875824,
    -1.2913037937660488,
    1.4577482623437266,
    4.206800318453501
  ],
  "_errors": [
    99.03534722511958,
    288.05034282222266,
    84.96469855181033
  ],
  "_errors_up": null,
  "_errors_down": null,
  "_metadata": {}
}
```

I guess everything needed to reconstruct the `Hist1D` is `bincounts()`, `binedges()`, `h.sumw2()`?
