### ISSUE TITLE
Overflow behavior

### ISSUE THREAD

**Issue by aminnj** [Moelf/FHist.jl#16]
Collecting discussion here on overflow handling. In my mind there are three ways of doing this:

1. the ROOT way: have extra underflow and overflow bins. If we don't want to deal with hackiness of changing the StatsBase histogram edges, then this would mean underflow and overflow counters in the `Hist1D` struct.

2. how it's done in `yahist`: `Hist1D(..., overflow=True)` by default (or `False`). This puts the overflow and underflow into the last or first bins rather than keep them separate like ROOT does.

3. let the user handle it: By default, anything outside the bin range is neglected. If the user wants to include overflows, they either extend the range or they `clamp()` values before filling the histogram.

* I think (3) is too annoying for HEP usecases. 
* (1) has the complication of extra infrastructure and when computing various statistics, do we include or exclude overflow? 
* I'm biased ;) but (2) seems like a sensible compromise which wouldn't be hard to implement (basically just `clamp()` inside the filling methods). And it makes the choice of including/excluding overflow at histogram construction time rather than arithmetic/statistic computation time. But it means that overflow/underflow can't be separated out after histogram construction (you'd need to reconstruct the histogram).

What are your thoughts?

**Comment by aminnj** [comment]
For future reference, all histogram filling is now done through `unsafe_push!()` so overflow logic goes in a single place.

```julia
@inline function unsafe_push!(h::Hist1D{T,E}, val::Real, wgt::Real=1) where {T,E}
    r = @inbounds h.hist.edges[1]
    L = length(r) - 1
    start = first(r)
    stop = last(r)
    c = ifelse(val > stop, 0, 1)
    c = ifelse(val < start, 0, c)
    binidx = _edge_binindex(r, val)
    binidx = ifelse(binidx > L, L, binidx)
    binidx = ifelse(binidx < 1, 1, binidx)
    @inbounds h.hist.weights[binidx] += c*wgt
    @inbounds h.sumw2[binidx] += c*wgt^2
    return nothing
end
```

**Comment by Moelf** [comment]
3 is too annoying to use in practice. 1 is okay, if not for the fact that plotting will need manual intervention. 2 is overall the best I think
