### ISSUE TITLE
cumulative reverse order

### ISSUE THREAD

**Issue by sgnoohc** [Moelf/FHist.jl#36]
Was the function meant to be cumsum(f( not f(cumsum( ? 

https://github.com/Moelf/FHist.jl/blob/0c3dfdf118600507fa6a38aa0208a855d1347fa3/src/hist1d.jl#L238-L239

**Comment by sgnoohc** [comment]
actually i think it's a bit more complicated if it's reversed.

**Comment by aminnj** [comment]
Ah I think it should’ve been f(cumsum(f())

**Comment by sgnoohc** [comment]
ah yes that. identiy of identity is identity ;)
