### ISSUE TITLE
Should there be a function return sumw2?

### ISSUE THREAD

**Issue by sgnoohc** [Moelf/FHist.jl#38]
Just a thought.
Feel free to ignore.

Just in case in future the data structure changes, having an accessor to "sumw2" information may be better than direct access of h.sumw2.

**Comment by Moelf** [comment]
Not against it but I think `sumw2` is an approximate handle on error anyway, so we might as well just provide some kind of functions that returns different kinds of errors directly.

**Comment by sgnoohc** [comment]
Yeah that would be nice.

**Comment by aminnj** [comment]
We have
```julia
bincounts(h::Hist1D) = h.hist.weights
binedges(h::Hist1D) = h.hist.edges[1]
```
should we just add
```julia
binerrors(h::Hist1D) = sqrt(h.sumw2)
```
? (with a caveat in the docstr that this only makes sense for gaussian errors--though this is the most common use case)

**Comment by Moelf** [comment]
maybe so they can do whatever they want:
```julia
binerrors(f::T, h::Hist1D) where T = f(h.sumw2)
binerrors(h::Hist1D) = binerrors(sqrt, h)
```
