### ISSUE TITLE
Naming of push/unsafe_push

### ISSUE THREAD

**Issue by aminnj** [Moelf/FHist.jl#48]
Should we rename
`unsafe_push` -> `push`
`push` -> `atomic_push`
?
(and then update docs to emphasize the difference). "atomic" also makes it clear what the safe/unsafe distinction refers to--thread safety.

That way people get good performance with the default `push!()`ing into a histogram. And it will still work in most use cases where threads operate on different chunks of data and fill thread-local histograms which are summed/merged later.

**Comment by Moelf** [comment]
this sounds better in light of the discussion at https://github.com/JuliaStats/StatsBase.jl/issues/704
