### ISSUE TITLE
High precision bin edges make overfull display

### ISSUE THREAD

**Issue by jlazar17** [Moelf/FHist.jl#57]
![image](https://user-images.githubusercontent.com/17930095/142662907-f2655492-a998-4198-b8b0-29eb9ace152b.png)

**Comment by Moelf** [comment]
My guess is if you round the `minimum(_e)` and maximum in:
https://github.com/Moelf/FHist.jl/blob/b6d9668fc77c33d2b09541020447430320466b6f/src/hist1d.jl#L348-L349

it should be fixed

**Comment by aminnj** [comment]
Fixed it in the above PR with `sigdigits=10` since that's about where overlap starts to happen and it doesn't hurt to make it as large as possible (you'll still only see `0.98329`).

**Comment by Moelf** [comment]
fixed in https://github.com/Moelf/FHist.jl/pull/56
