### ISSUE TITLE
Nonuniform weights?

### ISSUE THREAD

**Issue by henry2004y** [Moelf/FHist.jl#59]
Hi,

Thanks for sharing this package! I have a question of the option of nonuniform weights provided by the APIs. It seems like currently it is always assumed to have uniform weights 1. Is it possible to support a separate weight array input?

If so, I would really love to see the performance difference compared to, say, the 2D histogram plotting function such as
```python
h = histogram2d(v1, v2; bins=(r1, r2), weights)
```
from Matplotlib.

**Comment by Moelf** [comment]
We do support uniform weight, maybe documentation really need some help

**Comment by Moelf** [comment]
At the end of the docstring, we have
```julia
  Hist2D(A::AbstractVector{T}, wgts::AbstractWeights; nbins::NTuple{2,Integer}, overflow) where T


  Automatically determine number of bins based on Sturges algo.
```
![image](https://user-images.githubusercontent.com/5306213/154969657-952b46b8-07b5-4c53-9b67-9f867e597c55.png)


yeah could use some example in docs and probably a good idea to re-export `Weights`

**Comment by aminnj** [comment]
Regarding `FHist.Hist2D` vs `np.histogram2d`, this package is an order of magnitude faster because `np.histogram2d` uses binary search to get the bin index even when uniform bins are provided (and thus the bin index is directly calculable).

### 2D

#### julia
```julia
julia> a = randn(10^6);
julia> b = randn(10^6);
julia> @time Hist2D((a,b), (-3:0.1:3, -3:0.1:3));
  0.004413 seconds (12 allocations: 84.891 KiB)
# 4.4ms
```

#### python
```python
a = np.random.normal(0,1,10**6)
b = np.random.normal(0,1,10**6)
%timeit np.histogram2d(a, b, range=[(-3,3),(-3,3)], bins=(60,60))
90.4 ms ± 262 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

for 1D, `numpy` has an optimization to directly compute bin indices for uniformly spaced edges. But it makes several passes over the array to deal with literal edge cases. So the improvement provided by this package is not as large as for 2D, but it is still way faster

### 1D

#### julia
```julia
julia> @time Hist1D(a,-3:0.1:3)
  0.001728 seconds (8 allocations: 1.844 KiB)
# 1.7ms
```

#### python
```python
%timeit np.histogram(a, range=[-3,3], bins=60)
8.95 ms ± 73.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by henry2004y** [comment]
Now I have some test results from my data sample: 

```julia
julia> using PyCall
julia> np = pyimport("numpy")
julia> # v1 and v2 are 2808-element Vector{Float32}

julia> @time h2 = Hist2D((v1, v2), FHist.Weights(weights), (r1, r2));
  0.000064 seconds (10 allocations: 25.719 KiB)

julia> @time h, xedges, yedges = np.histogram2d(v1, v2, bins=(r1, r2), weights=weights);
  0.000648 seconds (225 allocations: 21.875 KiB)
```

At this sample size, the plotting time is essentially dominated by the plotting functions but not the histogram sorting. Interestingly, numpy has more allocation numbers but in total fewer memory allocated. Is that because In FHist we always compute things like `sumw2` while numpy `histogram2d` doesn't?

**Comment by Moelf** [comment]
I don't think you can benchmark python/C (numpy) allocation from Julia side like this
