### ISSUE TITLE
integral should take into account binwidths

### ISSUE THREAD

**Issue by alanedelman** [Moelf/FHist.jl#73]
this also affects normalize
so if one plots the normalized histogram one doesn't get an area under the curve of 1 as desired

**Comment by Moelf** [comment]
we model after this function:
https://root.cern.ch/doc/master/classTH1.html#aaf053a4b487c46b9e20c0bf534b34012

let me quickly check if they do something about bin-width;

maybe the answer is to only fix normalize

**Comment by alanedelman** [comment]
mostly i figure if the histogram knows its widths i shouldn't have to type it

if useful you might crossreference other histograms in the julia ecosystem:
https://github.com/mitmath/18338/blob/master/JuliaNotebooks/0.0%20Histogramming.ipynb
see the word `normalize` used in different ways

**Comment by Moelf** [comment]
we actually use `StatsBase` under the hood haha, but yeah, HEP is weird.

There's not enough bandwidth in the community rn but one day I wish we could have a separate histogram package and StatsBase use that one, and we can sort out different "properties" of histograms by using the type system (where now there's like `normalize` https://github.com/JuliaStats/StatsBase.jl/blob/39d0433f5044f8cafaa902cf31b3f83979585657/src/hist.jl#L190 field ad-hoc)

**Comment by Moelf** [comment]
ROOT's behavior when having variable bin width:
```python

In [10]: ROOT.TH1D("test", "test", 3, array.array("d", [0, 1, 2, 4]))
Out[10]: <cppyy.gbl.TH1D object at 0x5de8700>

In [11]: t.Fill(0.5, 0.5)
Out[11]: 1

In [12]: t.Fill(0.5, 0.5)
Out[12]: 1

In [14]: t
Out[14]: <cppyy.gbl.TH1D object at 0x605e730>

In [15]: t.Integral()
Out[15]: 1.0

In [16]: t.Fill(2.5, 0.5)
Out[16]: 3

In [17]: t.Integral()
Out[17]: 1.5

In [18]: t.Integral("width")
Out[18]: 2.0
```

as for different "normalize()", see discussion: https://root-forum.cern.ch/t/different-ways-of-normalizing-histograms/15582

## Method 4
```python
In [28]: t.Scale(1. / t.Integral())

In [29]: t.GetBinContent(3)
Out[29]: 0.3333333333333333
```

## Method 6
```python
# re-make t
In [30]: t = ROOT.TH1D("test", "test", 3, array.array("d", [0, 1, 2, 4]))
TROOT::Append:0: RuntimeWarning: Replacing existing TH1: test (Potential memory leak).

In [31]: t.Fill(0.5, 0.5)
Out[31]: 1

In [32]: t.Fill(0.5, 0.5)
Out[32]: 1

In [33]: t.Fill(2.5, 0.5)
Out[33]: 3

In [34]: t.Scale(1. / t.Integral("width"))

In [35]: t.GetBinContent(3)
Out[35]: 0.25

In [36]: t.Integral()
Out[36]: 0.75

In [37]: t.Integral("width")
Out[37]: 1.0
```
