### ISSUE TITLE
normalize, width = true

### ISSUE THREAD

**Issue by alanedelman** [Moelf/FHist.jl#78]
`true` should be the default
that would be consistent with everyone else's normalize
thanks

**Comment by Moelf** [comment]
so we often have histograms with "overflow" bins; since you don't have bin width information there, you can't take `integral` with width, thus can't `normalize` with `width=true`.

I do agree in statistics `width=true` makes most sense outside of high-energy physics.

**Comment by alanedelman** [comment]
seems like a tail wagging the dog thing to me
perhaps have width = unknown or something for overflow

**Comment by Moelf** [comment]
I see two solutions:
1. when dealing with overflow histograms, force `width=false`, hope user reads the manual
2. use the width of the overflow bin "as is", hope the approximation is what user wants.

**Comment by Moelf** [comment]
as you can see width is an explicit option one has to add to in the C++ Framework used wildy in the field:

https://root.cern/manual/histograms/#normalizing-histograms

let me try a PR idea

**Comment by Moelf** [comment]
https://juliastats.org/StatsBase.jl/stable/empirical/#LinearAlgebra.normalize

maybe we should adopt this interface (more work)
