### ISSUE TITLE
[RFC] `v0.11` breaking change to main API

### ISSUE THREAD

**Issue by Moelf** [Moelf/FHist.jl#91]
There are mainly three ways a user may want to construct a histogram:

1. Directly construct a histogram from known `binedges, bincounts, sumw2s, nentries` (e.g. loading histogram from ROOT)
2. Starting with a known histogram bin count type and `binedges`, then `push!()` into this histogram\
3. Starting with a bunch of data already in array (possibly with `weights` as well, maybe already know desired `binedges`)

Our current APIs are quite confusing, I want to re-design it, but there are ~maybe binary-choice~ some design questions we have to answer, I will say what they are and write down what I prefer for posterity:

## A) `fit(Hist1D, ...)` vs. B) `Hist1D(...)`

The first obvious question is do we want to use `Hist1D(...)` for everything or reserve it for constructor-like use case only. I prefer option B) because even if we use `fit()` for the 3nd kind of use case, use case 1. and 2. will still share `Hist1D(...)` api,

## Positional args vs. Keyword args
I would call use cases 1. and 2. "constructor-like" where 3. is "fit-like". Here we have one obvious choice (or the opposite), I have been thinking about something like this:

```julia
# constructor-like
Hist1D(; eltye::Type{T}, binedges, bincounts, sumw2s, nentries, overflow) where T

# fit-like
Hist1D(ary, weights, binedges; eltype::Type{T}, overflow) where T
```

we can as easily exchange these two, make `fit-like` use keyword argument. But somehow I feel like make constructir-like use case 100% explicit might be more natural

**Comment by Moelf** [comment]
## Default Inferability of positional arguments
- `eltype::Type{T}` can default to `Float64` because `maxintfloat(Float64) ~ 9e15`
- `binedges::AbstractVector` must be supplied by user
- `bincounts` can default to `zeros(T, length(binedges)+1)`
- `sumw2s` can default to `zeros(T, length(binedges)+1)`
- `nentries` can default to `0::Int64`
- `overflow` can default to `false`

```julia
function Hist1D(;
    eltye::Type{T}=Float64,
    binedges::AbstractVector,
    bincounts = zeros(T, length(binedges)-1),
    sumw2s = zero(bincounts),
    nentries = 0,
    overflow = false) where T

    length(binedges)-1 == length(bincounts) == length(sumw2s) || throw(DimensionMismatch())

end
```

**Comment by Moelf** [comment]
## Default & Inferability of fit-like
- `ary` - user must provide data
- `wgts` - user can provide a vector wrapped in `Weights` or leave it as `nothing`
- `binedges` - user can provide a vector or leave it as `nothing` (we can specialize on uniform binning)
- `eltype` same as constructor-like
- `overflow` same as constructor-like

```julia
function Hist1D(ary::AbstractVector{A},
    wgts::Union{Nothing, AbstractWeights} = nothing,
    binedges::Union{Nothing, AbstractVector} = nothing;
    eltype::Type{T} = Float64,
    overflow = false) where {A,T}

end
```

for automatically figuring out number of bins, we want to use https://github.com/JuliaPlots/Plots.jl/blob/42244b6aea99327acb07055d57bff2da41104555/src/recipes.jl#L719

**Comment by tamasgal** [comment]
B and "constructor-like" ;)

But if possible I'd also opt for `weights` and `array` instead of `wgts` and `ary` 🙈 

What about going for v1.0 with this?

**Comment by Moelf** [comment]
A) and B) are binary option but the constructor-like and fit-like can both be true at the same time.

>But if possible I'd also opt for weights and array instead of wgts and ary 🙈

for the fit-like API, these are positional argument so the name doesn't matter

- - -
>What about going for v1.0 with this?

yes that's the plan, we will do 0.11 as a mock up for 1.0

**Comment by Moelf** [comment]
It's also possible to not provide fit-like API at all, instead, we ask user to always do:
```julia
h1 = Hist1D(; binedges=...)
append!(h1, data, weights)
```

**Comment by tamasgal** [comment]
Yes indeed, offering the fit-like API additionally is of course fine.

> for the fit-like API, these are positional argument so the name doesn't matter

Well, they show up in the docs/docstring 😉

**Comment by Moelf** [comment]
yeah, I think this is clean enough:

- if you want to make an empty histogram for use later, call `Hist1D(; ...)` with empty positional argument
- if you want to one-shot making histogram from data, pass relevant info into positional arguments

**Comment by tamasgal** [comment]
Just one additional thought: when creating a one-shot histogram, we should ensure that that the object is also "valid" in some sense. Some sanity checks like equal lengths for counts and weights etc.

**Comment by Moelf** [comment]
yeah:
https://github.com/Moelf/FHist.jl/blob/b95f39edf383bc0306b48857c67de36a763cdaf9/src/hist1d.jl#L203

**Comment by tamasgal** [comment]
Sorry for my ignorance ;)
