### ISSUE TITLE
Pushing `-Inf` and `Inf`

### ISSUE THREAD

**Issue by tamasgal** [Moelf/FHist.jl#99]
I just bumped into an error when trying to push `-Inf` or `Inf` (also `NaN` but that's another topic) to a histogram. I wanted to create a PR but then found that there is already a commented-out codeline which fixes the problem and according to the comment it's even 20% faster.

Is there any reason not to use that line instead?

https://github.com/Moelf/FHist.jl/blob/b1a9b1cddb26a18fc1c35297564af468abe93e03/src/hist1d.jl#L17

The error btw. is:

```julia
julia> using FHist

julia> h = Hist1D(;bins=1:10)
edges: 1:10
bin counts: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
total count: 0.0

julia> push!(h, -Inf)
ERROR: InexactError: trunc(Int64, -Inf)
Stacktrace:
 [1] trunc
   @ ./float.jl:893 [inlined]
 [2] floor
   @ ./float.jl:382 [inlined]
 [3] _edge_binindex
   @ ~/.julia/packages/FHist/Gj41b/src/hist1d.jl:15 [inlined]
 [4] push!
   @ ~/.julia/packages/FHist/Gj41b/src/hist1d.jl:121 [inlined]
 [5] push!(h::Hist1D{Float64, Tuple{UnitRange{Int64}}}, val::Float64)
   @ FHist ~/.julia/packages/FHist/Gj41b/src/hist1d.jl:119
 [6] top-level scope
   @ REPL[11]:1
```

**Comment by Moelf** [comment]
That histogram doesn't have overflow bin enabled, so you shouldn't be able to push infinity into it?

**Comment by tamasgal** [comment]
Yes sorry I forgot to add that it also happens with `overflow=true` ;) Nevertheless, I think that in both cases it should not error, should it?

```julia
julia> using FHist

julia> h = Hist1D(;bins=1:10, overflow=true)
edges: 1:10
bin counts: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
total count: 0.0

julia> push!(h, -Inf)
ERROR: InexactError: trunc(Int64, -Inf)
Stacktrace:
 [1] trunc
   @ ./float.jl:893 [inlined]
 [2] floor
   @ ./float.jl:382 [inlined]
 [3] _edge_binindex
   @ ~/.julia/packages/FHist/Gj41b/src/hist1d.jl:15 [inlined]
 [4] push!
   @ ~/.julia/packages/FHist/Gj41b/src/hist1d.jl:121 [inlined]
 [5] push!(h::Hist1D{Float64, Tuple{UnitRange{Int64}}}, val::Float64)
   @ FHist ~/.julia/packages/FHist/Gj41b/src/hist1d.jl:119
 [6] top-level scope
   @ REPL[3]:1
```

**Comment by Moelf** [comment]
my take is that `Inf` is not physical, a physical quantity you put into histogram cannot actually be infinity, so users should handle it themselves to show intention.

**Comment by tamasgal** [comment]
Hm, yeah I agree that they are not so physical but sometimes these singularities are there ;) and if I want to count them outside of the bin-range, I need to hack it.

Anyways, It's probably fine like it is, I can get around with an extra `filter` before I push. We can close...
